package com.fitsupplepos.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Generates simple, clean PDF reports using OpenPDF. This is intentionally separate from
 * the (future) Invoice PDF generator — invoices need shop branding/logo/line-item layout,
 * while report PDFs are plain tabular summaries.
 */
public final class PdfReportService {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd-MMM-yyyy");
    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD);
    private static final Font HEADER_FONT = new Font(Font.HELVETICA, 11, Font.BOLD, Color.WHITE);
    private static final Font LABEL_FONT = new Font(Font.HELVETICA, 11, Font.BOLD);
    private static final Font VALUE_FONT = new Font(Font.HELVETICA, 11, Font.NORMAL);
    private static final Color HEADER_BG = new Color(15, 31, 61); // navy, matches app theme

    private PdfReportService() {}

    public static void writeProfitSummaryPdf(File file, LocalDate from, LocalDate to,
                                              ReportService.ProfitSummary summary) throws IOException {
        Document document = new Document(PageSize.A4, 40, 40, 50, 50);
        try (FileOutputStream out = new FileOutputStream(file)) {
            PdfWriter.getInstance(document, out);
            document.open();

            Paragraph title = new Paragraph("FitSupple POS — Profit & Loss Summary", TITLE_FONT);
            title.setSpacingAfter(4);
            document.add(title);

            Paragraph range = new Paragraph(
                    "Period: " + from.format(DATE_FMT) + " to " + to.format(DATE_FMT),
                    VALUE_FONT);
            range.setSpacingAfter(20);
            document.add(range);

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{60, 40});

            addHeaderRow(table, "Line Item", "Amount (₹)");
            addRow(table, "Revenue", summary.revenue());
            addRow(table, "Cost of Goods Sold", summary.costOfGoodsSold());
            addRow(table, "Discounts Given", summary.discounts());
            addRow(table, "Expenses", summary.expenses());
            addRow(table, "Gross Profit", summary.grossProfit());
            addRow(table, "Net Profit", summary.netProfit());

            document.add(table);

            Paragraph footer = new Paragraph(
                    "\nGenerated by FitSupple POS on " + LocalDate.now().format(DATE_FMT), VALUE_FONT);
            document.add(footer);
        } finally {
            if (document.isOpen()) {
                document.close();
            }
        }
    }

    private static void addHeaderRow(PdfPTable table, String col1, String col2) {
        PdfPCell c1 = new PdfPCell(new Phrase(col1, HEADER_FONT));
        c1.setBackgroundColor(HEADER_BG);
        c1.setPadding(8);
        PdfPCell c2 = new PdfPCell(new Phrase(col2, HEADER_FONT));
        c2.setBackgroundColor(HEADER_BG);
        c2.setPadding(8);
        c2.setHorizontalAlignment(Element.ALIGN_RIGHT);
        table.addCell(c1);
        table.addCell(c2);
    }

    private static void addRow(PdfPTable table, String label, java.math.BigDecimal value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, LABEL_FONT));
        labelCell.setPadding(6);
        PdfPCell valueCell = new PdfPCell(new Phrase(value.setScale(2, RoundingMode.HALF_UP).toPlainString(), VALUE_FONT));
        valueCell.setPadding(6);
        valueCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        table.addCell(labelCell);
        table.addCell(valueCell);
    }
}
